controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

ai_controllers:
    resource:
        path: ../src/Ai/Controller/
        namespace: App\Ai\Controller
    type: attribute

finance_controllers:
    resource:
        path: ../src/Finance/Controller/
        namespace: App\Finance\Controller
    type: attribute

loan_controllers:
    resource:
        path: ../src/Loan/Controller/
        namespace: App\Loan\Controller
    type: attribute

ozon_controllers:
    resource:
        path: ../src/Marketplace/Ozon/Controller/
        namespace: App\Marketplace\Ozon\Controller
    type: attribute

wildberries_controllers:
    resource:
        path: ../src/Marketplace/Wildberries/Controller/
        namespace: App\Marketplace\Wildberries\Controller
    type: attribute

admin:
    resource: routes/admin.yaml
