framework:
    rate_limiter:
        reports_api:
            policy: fixed_window
            limit: 60
            interval: '1 minute'
        registration:
            policy: fixed_window
            limit: 5
            interval: '10 minutes'
