sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        ignore_exceptions:
            - 'Symfony\Component\ErrorHandler\Error\FatalError'
            - 'Symfony\Component\Debug\Exception\FatalErrorException'

    # Отключаем стандартные перехватчики, ловим всё через Monolog
    register_error_listener: false
    register_error_handler: false

services:
    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR # Строго ERROR, никакого INFO
            $fillExtraContext: true
