twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/project_direction_picker_theme.html.twig'
    paths:
        '%kernel.project_dir%/templates/balance': Balance
        '%kernel.project_dir%/templates/loan': Loan
        '%kernel.project_dir%/templates/telegram': Telegram
        '%kernel.project_dir%/templates/marketplace': Marketplace
        '%kernel.project_dir%/templates/finance': Finance
        '%kernel.project_dir%/templates/partials': Partials

when@test:
    twig:
        strict_variables: true
